version: '3'

networks:
  inception:
    driver: bridge

volumes:
  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mbelbiad/data/wp_data
      o: bind
      type: none
  
  db_data:
    driver: local
    name: mariadb
    driver_opts:
      device: /home/mbelbiad/data/db_data
      o: bind
      type: none
 
services:

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        PASSWORD: 123
        USER: hola1
        PASS_USER: 147
        DATA_BASE: hola
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart : always
  
  wordpress:
    build: ./requirements/Wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart : always
  nginx:
    build: ./requirements/nginx
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception  
    restart: always
