version: '3'

networks:
  inception:
    name : inception

volumes:
  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /workspaces/inception/wp_data
      o: bind
      type: none
  
  db_data:
    name: mariadb
    driver: local
    driver_opts:
      device: /workspaces/inception/db_data
      o: bind
      type: none
 
services:

  mariadb:
    build: mariadb/.
    ports: 
      - "3306:3306"
    environment:
      DB_DATABASE: hola
      DB_USER: hola
      DB_PASSWORD: pass
      DB_ROOT_PASSWORD: pass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - inception
    # restart : always
  
  wordpress:
    build: Wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    # restart : always
  
  nginx:
    build: nginx/.
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - db_data:/var/www/html
    networks:
      - inception
    # restart: always
